version: '3.4'

services:
  e3projectmanagerwebapplication:
    image: e3projectmanagercontainerregistry.azurecr.io/e3projectmanager:stageDebug
    build:      
      dockerfile: Source/Debug.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=azurecontainerstage
      - ASPNETCORE_URLS=http://+:80      
    networks:
      - e3projectmanagerdevnet
    ports:
      - '80:80'
    depends_on:
      - mssql
    restart: on-failure
  mssql:
    container_name: e3projectmanagersql
    image:  "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "?5b0451546a750925ff20f2f72a036f70364c2cdf170c54ff0893d030e0e617f8"
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'
    networks:
      - e3projectmanagerdevnet
networks:
  e3projectmanagerdevnet:
    external: false
    name: e3projectmanagerdevnet