version: '3.4'

services:
  e3projectmanagerwebapplication:
    image: e3projectmanagercontainerregistry.azurecr.io/e3projectmanager:stageDebug
    build:      
      dockerfile: Source/Debug.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=azurecontainerstage
      - ASPNETCORE_URLS=http://+:80          
    ports:
      - '80:80'
